package utils;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.RemoteWebDriver;

public class BasePage {

    public BasePage(RemoteWebDriver driver) {
        this.driver = driver;

    }
    public WebDriver driver;

    public WebElement element(By Locator) {
        return driver.findElement(Locator);
    }
    public By satilikButton = By.cssSelector("section.home-wrapper:nth-child(2) div.home-search-wrap:nth-child(1) div.main-inner div.middle.home-content div:nth-child(2) ul.search-title-tab-list:nth-child(5) li:nth-child(1) a.btn.btn-search > span:nth-child(2)");
    public By ilSec = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCitySec:nth-child(2) div.filter-item-inner div.filter-select.grid-100 div.he-filter-control.he-select.js-city-filter div.he-filter-control__field div.he-select-base > div.he-select-base__container");
    public By izmir = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCitySec:nth-child(2) div.filter-item-inner div.filter-select.grid-100 div.he-filter-control.he-select.js-city-filter div.he-filter-control__field div.he-select-base div.he-popper.he-select-base__dropdown > input.he-select-base__search");
    public By listedenIlSec = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCitySec:nth-child(2) div.filter-item-inner div.filter-select.grid-100 div.he-filter-control.he-select.js-city-filter div.he-filter-control__field div.he-select-base div.he-popper.he-select-base__dropdown div.ps div.he-select-base__list > ul.he-select__list");
    public By ilceSec = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCountySec:nth-child(3) div.he-filter-control.he-multiselect.js-county-filter div.he-filter-control__field div.he-select-base > div.he-select-base__container");
    public By bornova = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCountySec:nth-child(3) div.he-filter-control.he-multiselect.js-county-filter div.he-filter-control__field div.he-select-base div.he-popper.he-select-base__dropdown > input.he-select-base__search");
    public By listedenIlceSec = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.locationSec:nth-child(1) section.filter-item-wrap.loc.locationCountySec:nth-child(3) div.he-filter-control.he-multiselect.js-county-filter div.he-filter-control__field div.he-select-base div.he-popper.he-select-base__dropdown div.ps div.he-select-base__list > ul.he-multiselect__list\"");
    public By enazFiyat = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.filter-item-wrap.priceSec:nth-child(4) div.filter-input div.floating-label.grid-48:nth-child(1) > input.floating-input.priceMin:nth-child(1)");
    public By encokFiyat = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.filter-item-wrap.priceSec:nth-child(4) div.filter-input div.floating-label.grid-48:nth-child(2) > input.floating-input.priceMax:nth-child(1)");
    public By binaYasi = By.xpath("//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/section[2]/div[1]/section[7]/section[1]/div[1]/div[1]");
    public By yas1 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.buildingAgeSec:nth-child(7) section.filter-item-wrap div.filter-item-inner div.dropdown-lightbox div.dropdown-wrap div.dropdown-flow ul.dropdown-list li:nth-child(1) > label.md-checkbox");
    public By yas2 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.left-content section.listing-filter div.listing-filter-inner section.buildingAgeSec:nth-child(7) section.filter-item-wrap div.filter-item-inner div.dropdown-lightbox div.dropdown-wrap div.dropdown-flow ul.dropdown-list li:nth-child(2) > label.md-checkbox");
    public By yas3 = By.xpath("//span[contains(text(),'6-10')]");
    public By araButton = By.xpath("//body/div[@id='__nuxt']/div[@id='__layout']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/section[2]/div[1]/section[24]/a[1]");
    public By deger1 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list li.applied-filters-list__group:nth-child(1) > span.applied-filters-list-item.last--item");
    public By deger2 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list li.applied-filters-list__group:nth-child(2) > span.applied-filters-list-item.last--item");
    public By deger3 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list li.applied-filters-list__group:nth-child(3) > span.applied-filters-list-item.last--item");
    public By deger4 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list li.applied-filters-list__group:nth-child(4) > span.applied-filters-list-item");
    public By deger5 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list > span.applied-filters-list-item:nth-child(5)");
    public By deger6 = By.cssSelector("div.list-page-master:nth-child(2) div.list-page-wrapper:nth-child(2) div.wrapper.list-wrapper:nth-child(2) div.container.no-flex-wrap div.right-content.content div.applied-filters.filters--expanded div.applied-filters__inner ul.applied-filters-list > span.applied-filters-list-item.last--item:nth-child(6)");
}
